services:
  api-gateway:
    image: minhtumtn/api-gateway:1.0
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - theducknote

  notification:
    image: minhtumtn/notification:1.0
    container_name: notification
    ports:
      - "8082:8082"
    networks:
      - theducknote
    depends_on:
      rabbitmq:
        condition: service_healthy

  profile:
    image: minhtumtn/profile:1.0
    container_name: profile
    ports:
      - "8081:8081"
    networks:
      - theducknote

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  theducknote:
    driver: bridge
