server:
  port: 8080
spring:
  application:
    name: api-gateway
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      mvc:
        routes:
          - id: profile
            uri: http://localhost:8081
            predicates:
              - Path=/api/profiles/**

logging:
  file:
    name: application.log
