server:
  port: 8080
spring:
  application:
    name: api-gateway
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://minhtumtn.ddns.net:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    # password: 0703
    hikari:
      password: "0703"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  rabbitmq:
    host: minhtumtn.ddns.net
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      mvc:
        routes:
          - id: profile
            uri: http://profile:8081
            predicates:
              - Path=/api/profiles/**

logging:
  file:
    name: application.log
